name: Node.js Integration Tests

on:
  pull_request:
    branches:
      - main  # This will trigger the workflow for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Run integration tests
        run: npm test
        env:
          NODE_ENV: test  # Set the environment to 'test'
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USERNAME: postgres  # Use the updated variable name
          DB_PASSWORD: kedarapte2004
          DB_NAME: kedardemo
