name: Node.js Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14  # Specify a stable version
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}  # Database username
          POSTGRES_PASSWORD: kedarapte2004  # New database password
          POSTGRES_DB: kedardemo  # Database name
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h postgres -p 5432 -U ${{ secrets.DB_USERNAME }}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: View PostgreSQL logs
        run: docker-compose logs postgres  # This might need adjusting based on your setup

      - name: Run integration tests
        run: npm test
        env:
          DB_HOST: postgres  # Use the service name for PostgreSQL
          DB_PORT: 5432
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: kedarapte2004
          DB_NAME: kedardemo
