name: Node.js Integration Tests

on:
  pull_request:
    branches:
      - main  # This will trigger the workflow for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.8  # Use a specific version of PostgreSQL
        ports:
          - 5432:5432  # Expose PostgreSQL on the standard port
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}  # Database name from secrets
          POSTGRES_USERNAME: ${{ secrets.DB_USER }}  # Database user from secrets
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Database password from secrets
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}" >> $GITHUB_ENV

      - name: Run integration tests
        run: npm test
        env:
          NODE_ENV: test  # Set environment to 'test'
          DATABASE_URL: ${{ env.DATABASE_URL }}  # Use constructed DATABASE_URL

