name: Node.js Integration Tests

on:
  pull_request:
    branches:
      - main  # This will trigger the workflow for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest  # Use the latest PostgreSQL image
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}  # Database username
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}  # New database password
          POSTGRES_DB: ${{ secrets.DB_NAME }}  # Database name
        ports:
          - 5432:5432  # Expose port 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h postgres -p 5432 -U ${{ secrets.DB_USERNAME }}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Run integration tests
        run: npm test
        env:
          DB_HOST: postgres  # Use the service name for PostgreSQL
          DB_PORT: 5432  # Specify the port explicitly
          DB_USERNAME: ${{ secrets.DB_USERNAME }}  # Match with POSTGRES_USER
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Use the new password directly
          DB_NAME: ${{ secrets.DB_NAME }}  # Use the newly created database name
