name: Build Packer Image on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  packer-build:
    if: github.event.pull_request.merged == true  # This ensures it runs only when PR is merged
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create zip file
      - name: Create zip file
        run: |
          zip -r project.zip . -x "*.git*"  # Zip the entire repository excluding .git
          ls -l  # List the files in the root directory to confirm zip file creation

      # Step 3: Set up AWS CLI (Dev account)
      - name: Set up AWS CLI (Dev account)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_GIT_ROLE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_GIT_ROLE_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust based on your region

      # Step 4: List files after AWS CLI setup
      - name: List files after AWS CLI setup
        run: |
          ls -l  # List files again to verify the AWS CLI setup did not alter anything

      # Step 5: Set up Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      # Step 6: Initialize Packer (using cd packer)
      - name: Initialize Packer
        run: |
          cd packer  # Change to the packer directory
          ls -l  # List the files inside the `packer` directory
          packer init kedarwebapp.pkr.hcl  # Initialize Packer from the HCL file in the current directory
          
      # Step 7: Run Packer Build (with machine-readable output)
      - name: Run Packer Build
        run: |
          cd packer  # Change to the packer directory
          set -x  # Enable script debugging
          packer build -debug -machine-readable -var "aws_region=us-east-1" kedarwebapp.pkr.hcl > packer_output.txt || { echo 'Packer build failed'; cat packer_output.txt; exit 1; }
          ls -l  # List the files in the current directory to confirm packer_output.txt was created
          
      # Step 8: Set up AWS CLI (Demo account)
      - name: Set up AWS CLI (Demo account)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEMO_GIT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEMO_GIT_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust based on your region

      # Step 9: List files after AWS CLI setup (Demo account)
      - name: List files after AWS CLI setup (Demo account)
        run: |
          ls -l  # List files to verify no unexpected changes after setting up Demo AWS credentials

      # Step 10: Check Packer output and Set AMI ID from Packer output
      - name: Check Packer output and Set AMI ID from Packer output
        run: |
          cd packer  # Change to the packer directory
          cat packer_output.txt  # Display the contents of the Packer output file
          AMI_ID=$(grep -oP '(?<=ami-)[\w\d]+' packer_output.txt | head -n 1)
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      # Step 11: Create New Launch Template Version (Demo)
      - name: Create New Launch Template Version (Demo)
        run: |
          aws ec2 create-launch-template-version \
            --launch-template-name kedar-web-app-launch-template \
            --version-description "New version with latest AMI" \
            --launch-template-data "ImageId=${{ env.AMI_ID }}"
          ls -l  # Verify directory contents after launch template version creation

      # Step 12: Update ASG with Latest Launch Template Version (Demo)
      - name: Check Packer output and Set AMI ID from Packer output
        run: |
          cd packer  # Change to the packer directory
          cat packer_output.txt  # Display the contents of the Packer output file
          AMI_ID=$(grep -oP 'ami-[\w\d]+' packer_output.txt | head -n 1)
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      # Step 13: Start Instance Refresh and Monitor (Demo)
      - name: Start Instance Refresh and Monitor (Demo)
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name kedar-web-app-asg \
            --query 'InstanceRefreshId' \
            --output text)
          echo "Started instance refresh with ID $REFRESH_ID"
          ls -l  # List files to confirm setup before entering the monitoring loop
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name kedar-web-app-asg \
              --query "InstanceRefreshes[?InstanceRefreshId=='$REFRESH_ID'].Status" \
              --output text)
            echo "Current refresh status: $STATUS"
            if [[ "$STATUS" == "Successful" ]]; then
              echo "Instance refresh completed successfully."
              exit 0
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" ]]; then
              echo "Instance refresh failed or was cancelled."
              exit 1
            else
              echo "Instance refresh in progress. Checking again in 30 seconds..."
              sleep 30
            fi
          done
